Create modules to export in index.js file
yusufnviiri/bookApp-ES6 pull request #1
Opened 2022-04-28 03:20 UTC by yusufnviiri

-Create folder modules.
-Create JavaScript modules using ES6 import and export functions
-Add luxon library
-Create index.HTML and  index.CSS files

2022-04-28 04:05 UTC, Mihndim2020 requested changes
### Hi @yusufnviiri, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Clean are organized code.
:heavy_check_mark: Your project is running free of `Linter errors`.

There are some issues that you still need to work on to get this project approved, but you are almost there!
![ALMOST-MINION](https://user-images.githubusercontent.com/65852621/133680327-431cb21d-ad7c-483a-84eb-21b733980a04.png)

# Status: Requires Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-28 04:05 UTC, Mihndim2020 commented on README.md
> +
- [ ] Please your `Readme file` will be more presentable and professional if you place each point on it's own line. Some like so: 
- cd awesome books
- open index.html in the editor/browser to view the project contents
- open style.css to see the CSS styles used in the project.
- enjoy
To make each point appear on it's own line, leave a single space between the stroke and the first character on the line. Please kindly fix that.

2022-04-28 04:05 UTC, Mihndim2020 commented on README.md
> + https://yusufnviiri.github.io/bookApp-ES6/
- [ ] Please you can delete this if the `Live demo`is not available, as this will make your readme file clean and professional.

2022-04-28 04:53 UTC, Lameck1 approved these changes
Hi, @yusufnviiri,

You've done well working on the concerns from the previous review 👏🏼.
Tasks for this project are now successfully implemented 💯.

### Highlights
- Professional README ✔️
- Clean code ✔️ 
- Good commit messages ✔️ 

All the best with the next project.

You are free to merge this branch :shipit:
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 15:52 UTC, merged

2022-05-03 07:43 UTC, khitermedachraf reviewed
Hello @yusufnviiri 👋 you did Amazing work 🥇 .
- Clean Code 👍 .
- Github workflow 👍 .
- Professional README ✔️
Here are some best practices you can always implement to improve the quality of code because yours is great:

- Form fields have no labels, it would be good practice to add labels to your form
- It would be great if you used semantic tags
- Your commit messages should be more descriptive and precise
- Also it is best practice to begin committing messages with caps so kindly consider that in subsequent commits